# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Tests,Kernel.php}'

    App\Infrastructure\Messenger\SimpleQueryBus:
      arguments:
        $container: '@service_container'


    # QueryBus
    App\Domain\Messenger\Query\Video\ImportVideosHandler:
        public: true
        arguments:
          $sourceRepository: '@App\Infrastructure\Persistence\Source\InMemorySourceRepository'
          $documentProvider: '@App\Infrastructure\Document\DocumentProvider'
          $documentMapper: '@App\Infrastructure\Document\DocumentMap\Video\DocumentMapVideo'
          $videoRepository: '@App\Infrastructure\Persistence\Video\InMemoryVideoRepository'
